apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-hostpath
  labels:
    app: mongo-hostpath
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi