apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogsapp
spec:
  selector:
    matchLabels:
      app: dogsapp
  template:
    metadata:
      labels:
        app: dogsapp
    spec:
      containers:
      - name: dogsapp
        image: 811653861373.dkr.ecr.us-east-1.amazonaws.com/k8s_ecr_repo:dogsv2
        ports:
        - containerPort: 80
