---
apiVersion: v1
kind: Pod
metadata:
  name: fortune
  labels:   
    app: fortune
spec:
  containers:
    - image: luksa/fortune
      name: html-generator
      ports:
        - containerPort: 80
          protocol: TCP
  