apiVersion: v1
kind: Pod
metadata:
  name: mongodb-aws
  labels:
    app: mongodb
spec:
  containers:
  - image: 811653861373.dkr.ecr.us-east-1.amazonaws.com/k8s_ecr_repo:mongodb
    name: mongodb
    ports:
    - containerPort: 80
      protocol: TCP
