apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
  labels:
    app: mongo-claim
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi