apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim
  labels:
    app: claim
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi